on:
  - push

jobs:
  deploy:
    if: github.ref_name == 'main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
      - run: mv build/libs/user-agent.jar .
      - run: docker compose -p user-agent -f docker/docker-compose.yml up -d --build
